[build]
pre-build = [
    # Use Azure mirrors for faster downloads
    "sed -i -e 's/archive.archive.ubuntu.com/azure.archive.ubuntu.com/' /etc/apt/sources.list",
    "sed -i -e 's/security.archive.ubuntu.com/azure.archive.ubuntu.com/' /etc/apt/sources.list",

    # Enable multiarch and install the necessary dependencies
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get -y install libclang-8-dev zlib1g-dev:$CROSS_DEB_ARCH",

    "curl -sL https://sentry.io/get-cli/ | sh",
]

[target.aarch64-unknown-linux-gnu]
# We're using a nightly `cross`, let's still use a stable image.
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
env.passthrough = ["CMAKE_TOOLCHAIN_FILE_aarch64_unknown_linux_gnu="]
